# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='invest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invest_name', models.CharField(max_length=200)),
                ('no', models.CharField(max_length=200)),
                ('risk', models.FloatField()),
                ('benefit', models.FloatField()),
                ('lost', models.FloatField()),
                ('mobility', models.IntegerField()),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='lognote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=300)),
                ('flag', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='myindex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rm', models.FloatField()),
                ('Rf', models.FloatField()),
                ('risk_m2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('type', models.IntegerField()),
                ('choice_a', models.CharField(max_length=200)),
                ('num_a', models.IntegerField()),
                ('choice_b', models.CharField(max_length=200)),
                ('num_b', models.IntegerField()),
                ('choice_c', models.CharField(max_length=200)),
                ('num_c', models.IntegerField()),
                ('choice_d', models.CharField(max_length=200)),
                ('num_d', models.IntegerField()),
                ('choice_e', models.CharField(max_length=200)),
                ('num_e', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('password', models.CharField(default='', max_length=200)),
                ('nickname', models.CharField(max_length=200)),
                ('score', models.IntegerField()),
                ('risk', models.FloatField()),
                ('mobility_a', models.FloatField()),
                ('mobility_b', models.FloatField()),
                ('mobility_c', models.FloatField()),
                ('mobility_d', models.FloatField()),
                ('risk_o', models.FloatField()),
                ('size', models.FloatField()),
                ('balance', models.FloatField()),
                ('max_re', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='user_his',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('balance', models.FloatField()),
                ('size', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='user_invest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField()),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('invest_type', models.IntegerField()),
                ('invest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.invest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
